---
title: "Project"
author: "Ian Curtis"
date: "`r Sys.Date()`"
output: html_document
---

# Import Packages and Data

```{r}
library(tidyverse)
library(lubridate)
library(yardstick)
library(caret)
library(rpart)
library(rpart.plot)
```

```{r import_data}
mlb_raw <- read_csv("mlb-hit-dist/mlb_hit_dist.csv") %>% 
  rename(hit_distance = hit_distance_sc) %>% 
  filter(
    (hit_distance > 15) & (!is.na(release_speed)) & (strikes < 3) & (!is.na(release_spin_rate)) & (description != 'foul') & (!events %in% c('sac_bunt', 'catcher_interf')) & (inning < 10))
```

# Data Tidying and Preprocessing

```{r transform_add_data}
mlb_transform <- mlb_raw %>% 
      mutate(
        pitch_type = ifelse(mlb_raw$pitch_type %in% c('CS', 'FS', 'KC', 'KN', 'EP', 'FA'), 'other', mlb_raw$pitch_type),
        sqrt_pitch_num = sqrt(pitch_number),
        month = month(game_date),
        dist_categ = as.factor(case_when(
          (hit_distance <= 70) ~ 'Zone 1',
          (hit_distance > 70 & hit_distance <= 140) ~ 'Zone 2',
          (hit_distance > 140 & hit_distance <= 210) ~ 'Zone 3',
          (hit_distance > 210 & hit_distance <= 280) ~ 'Zone 4',
          (hit_distance > 280 & hit_distance <= 350) ~ 'Zone 5',
          (hit_distance > 350) ~ 'Zone 6',
        )
        ))
```

```{r select_dummy_interact}
mlb_reduced <- mlb_transform %>% 
  select(!c(game_date, description, events, pitch_name, at_bat_number, home_team, pitch_number)) %>% 
  mutate(
    d_pitch_SI = ifelse(pitch_type == "SI", 1, 0),
    d_pitch_FC = ifelse(pitch_type == "FC", 1, 0),
    d_pitch_FF = ifelse(pitch_type == "FF", 1, 0),
    d_pitch_CU = ifelse(pitch_type == "CU", 1, 0),
    d_pitch_SL = ifelse(pitch_type == "SL", 1, 0),
    d_pitch_CH = ifelse(pitch_type == "CH", 1, 0),
    d_stand_l = ifelse(stand == 'L', 1, 0),
    d_pthrow_l = ifelse(p_throws == "L", 1, 0),
    d_inning_top = ifelse(inning_topbot == 'Top', 1, 0),
    i_release_balls = release_speed*balls,
    i_release_outs = release_speed*outs_when_up,
    i_release_inn = release_speed*inning,
    i_release_launchs = release_speed*launch_speed,
    i_release_launcha = release_speed*launch_angle,
    i_release_spin = release_speed*release_spin_rate,
    i_release_pitchn = release_speed*sqrt_pitch_num,
    i_release_SI = release_speed*d_pitch_SI,
    i_release_FC = release_speed*d_pitch_FC,
    i_release_FF = release_speed*d_pitch_FF,
    i_release_CU = release_speed*d_pitch_CU,
    i_release_SL = release_speed*d_pitch_SL,
    i_release_CH = release_speed*d_pitch_CH,
    i_ball_strike = balls*strikes,
    i_launches = launch_speed*launch_angle,
    i_spin_month = release_spin_rate*month,
    i_launchs_spin = launch_speed*release_spin_rate,
    i_launcha_spin = launch_angle*release_spin_rate
  ) %>% 
  select(!c(pitch_type, stand, p_throws, inning_topbot)) %>% 
  na.omit()
```

```{r split_data}
train <- mlb_reduced %>% sample_frac(.85)
test  <- anti_join(mlb_reduced, train)
```

Field Breaking points

* 0 - 70
* 71 - 140
* 141 - 210
* 211 - 280
* 281 - 350
* 351+

# Regression Analysis

## Full Model

```{r}
olsr <- function(model_name, data) {
  
  # Y vector of all dependent variable values
  Y <- data$hit_distance

  # X vector of all independent variable terms (with spot for intercept)
  intercept <- rep(1, nrow(data)) # large vector of ones
  almostX <- data %>% select(-c(hit_distance, dist_categ)) # take out the dependent variable
  X <- as.matrix(cbind(intercept, almostX)) # put intercept vector at beginning

  # X'X matrix
  Xt <- t(X) # transpose of the X independent values
  XtX <- Xt %*% X # multiply the X and its transpose

  XtXi <- solve(XtX)

  # X'y matrix
  XtY <- Xt %*% Y

  # Beta parameter estimations for the least squares line
  B <- XtXi %*% XtY

  # Predicted values using the generated beta estimations
  y_hat <- X %*% B

  # Residuals (error)
  e <- Y - y_hat

  # Sum of Squares
  sst <- (t(Y) %*% Y) - (nrow(data) * mean(Y)**2)
  sse <- t(e) %*% e
  ssr <- sst - sse
  msr <- ssr / (ncol(data) - 1)
  mse <- sse / (nrow(data) - ncol(data))
  
  # R squared
  r2 <- ssr / sst
  
  s2 <- sse / (nrow(data) - ncol(data))
  
  vcov <- matrix(unlist(drop(s2) * XtXi), ncol = ncol(data))
  stderr <- sqrt(diag(vcov))
  t <- B / stderr
  p_t <- dt(t, df = nrow(data) - ncol(data))
  p_t <- lapply(list(p_t), round, 4)

  #maybe?
  mallows_cp <- (sse / (nrow(data) - ncol(data))) + ((2 * ncol(data)) - nrow(data))
  
  f <- msr / mse
  p_overall <- round(pf(f, ncol(data) - 1, nrow(data) - ncol(data), lower.tail = F), 4)
  
  results <- list('model' = model_name, 'betas' = B, 'predicted' = y_hat, 'errors' = e, 'sst' = sst, 'sse' = sse, 'ssr'= ssr, 'msr' = msr, 'mse' = mse, 'r2' = r2, 's2' = s2, 'std_errs' = stderr, 't' = t, 'p_t' = p_t, 'mallows_cp' = mallows_cp, 'f' = f, 'p_overall' = p_overall)
  
  return(results)
}

evaluate_reg <- function(reg_output) {
  toadd <- c(reg_output['model'], reg_output['sst'], reg_output['sse'], reg_output['ssr'], reg_output['msr'], reg_output['mse'], reg_output['r2'], reg_output['s2'], reg_output['mallows_cp'], reg_output['f'], reg_output['p_overall'])
  
  return(toadd)
}
```

```{r}
full_model <- olsr('full', train)
full_model['p_t']
```

```{r}
RM1 <- train %>% 
  select(-c(balls, strikes, outs_when_up, inning, month, d_stand_l, d_pthrow_l, i_release_balls, i_release_inn, i_release_spin, i_ball_strike, i_spin_month))

reduced1 <- olsr('RM1', RM1)
reduced1['p_t']
```

```{r}
RM2 <- RM1 %>% 
  select(-c(i_release_outs, i_release_SI, i_release_FC, i_release_FF, i_release_CU, i_release_SL, i_release_CH), -starts_with('d_pitch'))

reduced2 <- olsr('RM2', RM2)
reduced2['p_t']
```

```{r}
RM3 <- train %>% 
  select(-c(i_release_SI, i_release_FC, i_release_FF, i_release_CU, i_release_SL, i_release_CH, balls, strikes, outs_when_up, inning, month), -starts_with('d_pitch'))
reduced3 <- olsr('RM3', RM3)

reduced3['p_t']
```

```{r}
RM4 <- RM3 %>% 
  select(-c(d_stand_l, d_pthrow_l, i_release_outs, i_release_inn, i_release_spin, d_inning_top))

reduced4 <- olsr('RM4', RM4)
reduced4['p_t']
```

```{r}
RM5 <- train %>% select(hit_distance, dist_categ, launch_angle, launch_speed, release_spin_rate, sqrt_pitch_num, i_release_launcha, i_release_launchs, i_launches, i_launcha_spin)

reduced5 <- olsr('RM5', RM5)
reduced5['p_t']
```

```{r}
eval_reg <- bind_rows(evaluate_reg(full_model), evaluate_reg(reduced1), evaluate_reg(reduced2), evaluate_reg(reduced3), evaluate_reg(reduced4), evaluate_reg(reduced5))
```

```{r}
resid_plot <- as_tibble(c(reduced5['errors'], reduced5['predicted'])) %>% 
  ggplot(aes(x = predicted, y = errors)) +
  geom_point()
ggsave('resid_plot.png')
```

```{r}
trainReg <- train %>% mutate(
  yhat = as_vector(reduced5['predicted']),
  pred_dist_categ = as.factor(case_when(
          (yhat <= 70) ~ 'Zone 1',
          (yhat > 70 & yhat <= 140) ~ 'Zone 2',
          (yhat > 140 & yhat <= 210) ~ 'Zone 3',
          (yhat > 210 & yhat <= 280) ~ 'Zone 4',
          (yhat > 280 & yhat <= 350) ~ 'Zone 5',
          (yhat > 350) ~ 'Zone 6',
        )),
)
```

```{r}
confusionMatrix(trainReg$pred_dist_categ, trainReg$dist_categ)
```

```{r}
testReg <- test %>% 
  select(hit_distance, dist_categ, launch_speed, launch_angle, release_spin_rate, sqrt_pitch_num, i_release_launcha, i_release_launchs, i_launches, i_launcha_spin)

testRegRes <- olsr('test', testReg)
```

```{r}
testReg <- testReg %>% mutate(
  yhat = as_vector(testRegRes['predicted']),
  pred_dist_categ = as.factor(case_when(
          (yhat <= 70) ~ 'Zone 1',
          (yhat > 70 & yhat <= 140) ~ 'Zone 2',
          (yhat > 140 & yhat <= 210) ~ 'Zone 3',
          (yhat > 210 & yhat <= 280) ~ 'Zone 4',
          (yhat > 280 & yhat <= 350) ~ 'Zone 5',
          (yhat > 350) ~ 'Zone 6',
        )),
)
```

```{r}
confusionMatrix(testReg$pred_dist_categ, testReg$dist_categ)
```

# Decision Tree Analysis

```{r}
dtree <- rpart(
  formula = dist_categ ~ launch_speed + launch_angle + release_speed + balls + strikes + outs_when_up + inning + release_spin_rate + sqrt_pitch_num + month + d_pitch_SI + d_pitch_FC + d_pitch_FF + d_pitch_CU + d_pitch_SL + d_pitch_CH + d_stand_l + d_pthrow_l + d_inning_top,
  data = train,
  parms = list(split="information")
)
summary(dtree)
```

```{r}
pdf("decision_tree.pdf")
rpart.plot(dtree)
dev.off()
```

```{r}
dtreeT <- rpart(
  formula = dist_categ ~ launch_speed + launch_angle,
  data = train,
  parms = list(split="information")
)


```

```{r}
rpart.plot(dtreeT)
```


# Neural Network Analysis
